server:
  servlet:
    context-path: /merchant-service

config:
  mysql:
    db: flash_merchant_service

spring:
  boot:
    admin:
      client:
        username: yueliminvc@outlook.com
        password: yueliminvc@outlook.com
        url: http://127.0.0.1:8849
