#spring:
#  servlet:
#    multipart:
#      # 默认支持文件上传.
#      enabled: true
#      # 支持文件写入磁盘.
#      file-size-threshold: 0
#      # 上传文件的临时目录
#      location:
#      # 最大支持文件大小
#      max-file-size: 1MB
#      # 最大支持请求大小
#      max-request-size: 30MB

server:
  servlet:
    context-path: /merchant

swagger:
  enable: true

spring:
  boot:
    admin:
      client:
        username: yueliminvc@outlook.com
        password: yueliminvc@outlook.com
        url: http://127.0.0.1:8849

sms:
  name: "sms"
  url: "http://127.0.0.1:56085/tencent"
  effectiveTime: "300"

minio:
  url: "http://127.0.0.1:56090/minio"
  id: "990fa03243584e9cbe71e5cfa8524e31"
  ak: "JDJhJDEwJDFjaTVhSWVRMWpTbTFjcXdmUENkeC5ndDI5R2FHR2J1YUtVL1ROZ24wWUNLR1JESnBMTmg2"
  sk: "JDJhJDEwJDFjaTVhSWVRMWpTbTFjcXdmUENkeC5nUUw0RnJsRkxodVkzRWlkbXVJQ0NEc1ZYOWhoM2dL"
