server:
  servlet:
    context-path: /operation

swagger:
  enable: true

spring:
  boot:
    admin:
      client:
        username: yueliminvc@outlook.com
        password: yueliminvc@outlook.com
        url: http://127.0.0.1:8849
